name: 'App deploy action script to ENONIC XP'
description: 'Github action script to be used for app deployment'
inputs:
  url: 
    description: 'URL to XP instance'
    required: true
  username:  
    description: 'user name'
    required: true
  password: 
    description: 'password of deploy user'
    required: true
  client_key:  
    description: 'Client key, required only for MTLS session'
    required: false
  client_cert: 
    description: 'Client cert, required only for MTLS session'
    required: false
  app_jar:  
    description: 'Path to the app to be deployed'
    required: true
    default: './build/libs/*.jar'

runs:
  using: "composite"
  steps:
    - name: Deploy
      env:
        XP_URL: ${{ inputs.url }}
        XP_USERNAME: ${{ inputs.username }}
        XP_PASSWORD: ${{ inputs.password }}
        CLIENT_KEY: ${{ inputs.client_key }}
        CLIENT_CERT: ${{ inputs.client_cert }}
        APP_JAR: ${{ inputs.app_jar }}
      run: |
        chmod +x ${{ github.action_path }}/deploy.sh
        bash ${{ github.action_path }}/deploy.sh
      shell: bash
